services:
  - type: web
    name: stokmate-api
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    healthCheckPath: /swagger/index.html
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
